askari/core/urls.py
from django.conf.urls import patterns, include, url
from .views import DashboardView

urlpatterns = patterns(
    '',
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),

    url(r'^databases/', include('askari.databases.urls', 
                                namespace="databases")),
    url(r'^dataclips/', include('askari.dataclips.urls', 
                                namespace="dataclips")),
)

askari/databases/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here
from .views import (DatabaseCreateView, DatabaseListView, DatabaseUpdateView,
    DatabaseDeleteView,)

urlpatterns = patterns('',
    url(r'^new/', DatabaseCreateView.as_view(), name='new'),
    url(r'^(?P<pk>[\d]+)/edit$', DatabaseUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>[\d]+)/delete$', DatabaseDeleteView.as_view(), name='delete'),
    url(r'^$', DatabaseListView.as_view(), name='list')
)

askari/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .core.views import UserRegistrationView, UserLoginView


# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^login/$', 'django.contrib.auth.views.login', 
                     {"template_name": 'core/login.html'}, 
                     name='login'),

    url(r'^register/$', UserRegistrationView.as_view(), name='registration'),

    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', 
                      name='logout'),

    url(r'^success_login/$', UserLoginView.as_view(), name='login_redirect'),
    url(r'^(?P<organization>\w+)/', include('askari.core.urls')),
)

askari/databases/models.py
from django.db import models


class Database(models.Model):
    ENGINE_CHOICE_MYSQL = ('mysql', 'MySQL')
    ENGINE_CHOICE_POSTGRES = ('postgres', 'PostgreSQL')

    ENGINE_CHOICES = (
        ENGINE_CHOICE_MYSQL,
        ENGINE_CHOICE_POSTGRES,
    )

    name = models.CharField(max_length=60)
    db_name = models.CharField(max_length=255)
    db_host = models.CharField(max_length=255)
    db_user = models.CharField(max_length=255)
    db_password = models.CharField(max_length=255, blank=True)
    db_engine = models.CharField(max_length=255, choices=ENGINE_CHOICES)
    user = models.ForeignKey('auth.User', 
                             null=True, 
                             blank=True, 
                             on_delete=models.DO_NOTHING)
    organization = models.ForeignKey('organizations.Organization', 
                                     on_delete=models.CASCADE)

    def __unicode__(self):
        return self.name

askari/databases/forms.py
from django import forms
from .models import Database


class DatabaseForm(forms.ModelForm):
    class Meta:
        model = Database
        exclude = ['user', 'organization']

askari/databases/views.py
# Create your views here.
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.core.urlresolvers import reverse
from ..core.mixins import LoginRequiredViewMixin, GenericTemplateDataMixin
from .models import Database
from .forms import DatabaseForm


class DatabaseMixin(GenericTemplateDataMixin, LoginRequiredViewMixin):
    model = Database

    def get_queryset(self):
        qs = super(DatabaseMixin, self).get_queryset()
        return qs & self.request.user.database_set.all()


class DatabaseFormMixin(DatabaseMixin):
    form_class = DatabaseForm

    def get_success_url(self):
        return reverse('databases:list', kwargs={
            'organization': self.organization.slug})


class DatabaseCreateView(DatabaseFormMixin, CreateView):
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.organization = self.organization
        return super(DatabaseCreateView, self).form_valid(form)


class DatabaseUpdateView(DatabaseFormMixin, UpdateView):
    pass


class DatabaseListView(DatabaseMixin, ListView):
    pass


class DatabaseDeleteView(DatabaseFormMixin, DeleteView):
    pass

askari/databases/templates/databases/database_confirm_delete.html
<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>

askari/databases/templates/databases/database_form.html
{% extends 'app_template.html' %}
{% load bootstrap3 %}

{% block main_content %}
    <section class="content-header">
        <h1>
            Banco de dados
            <small>Cadastro</small>
        </h1>

    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <form action="" method="POST" novalidate>
                        <div class="box-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </section>


{% endblock %}

askari/databases/templates/databases/database_list.html
{% extends 'app_template.html' %}

{% block main_content %}

    <section class="content-header">
        <h1>
            Banco de dados
            <small>listagem</small>
        </h1>

        <div class="pull-right">
            <a href="{% url 'databases:new' view.kwargs.organization %}" class="btn btn-success" style="margin-top: -55px;">
                <i class="fa fa-plus"></i>
                &nbsp;&nbsp;
                <strong>Adicionar</strong>
            </a>
        </div>
    </section>

    <section class="content">

        <div class="row">

            <div class="col-xs-12">

                <div class="box">

                    <div class="box-body table-responsive no-padding">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Database</th>
                                    <th>Host</th>
                                    <th>Tipo</th>
                                    <th>Dataclips</th>
                                    <th>Ações</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for resource in object_list %}
                                    <tr>
                                        <td>{{ resource.name }}</td>
                                        <td>{{ resource.db_name }}</td>
                                        <td>{{ resource.db_host }}</td>
                                        <td><span class="label label-info">{{ resource.db_engine }}</span></td>
                                        <td><span class="label label-danger">{{ resource.clip_set.all|length }}</span></td>
                                        <td>
                                            <div class="btn-group">
                                                <a data-toggle="tooltip" data-placement="top" title="Editar" href="{% url 'databases:edit' organization=view.kwargs.organization pk=resource.pk %}" class="btn btn-default btn-sm">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <a data-toggle="tooltip" data-placement="top" title="Apagar" href="{% url 'databases:delete' organization=view.kwargs.organization pk=resource.pk %}" class="btn btn-default btn-sm">
                                                    <i class="fa fa-trash-o"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>

        </div>

    </section>

{% endblock %}

{#    <ul>#}
{#      {% for resource in object_list %}#}
{#      <li>#}
{#        <a href="{% url 'databases:edit' pk=resource.pk %}">{{ resource.name }}</a>#}
{#        <a href="{% url 'databases:delete' pk=resource.pk %}">delete</a>#}
{#      </li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#    <a href="{% url 'databases:new' %}">Adicionar nova database</a>#}