askari/core/urls.py
from django.conf.urls import patterns, include, url
from .views import DashboardView

urlpatterns = patterns(
    '',
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),

    url(r'^databases/', include('askari.databases.urls', 
                                namespace="databases")),
    url(r'^dataclips/', include('askari.dataclips.urls', 
                                namespace="dataclips")),
)

askari/dataclips/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

from .views import ClipCreateView, ClipUpdateView, ClipDeleteView, ClipListView, ClipPublicView


urlpatterns = patterns('',
    url(r'^$', ClipListView.as_view(), name='list'),
    url(r'^new/', ClipCreateView.as_view(), name='new'),
    url(r'^(?P<pk>[\d]+)$', ClipUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w\d]+)/public$', ClipPublicView.as_view(), name='public'),
    url(r'^(?P<pk>[\d]+)/delete$', ClipDeleteView.as_view(), name='delete'),
    #url(r'^(?P<pk>[\d]+)/edit$', DatabaseUpdateView.as_view(), name='edit'),
    #url(r'^(?P<pk>[\d]+)/delete$', DatabaseDeleteView.as_view(), name='delete'),
    #url(r'^$', DatabaseListView.as_view(), name='list')
)

askari/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .core.views import UserRegistrationView, UserLoginView


# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^login/$', 'django.contrib.auth.views.login', 
                     {"template_name": 'core/login.html'}, 
                     name='login'),

    url(r'^register/$', UserRegistrationView.as_view(), name='registration'),

    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', 
                      name='logout'),

    url(r'^success_login/$', UserLoginView.as_view(), name='login_redirect'),
    url(r'^(?P<organization>\w+)/', include('askari.core.urls')),
)

askari/dataclips/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

import json

from django.core.cache import cache
from django.db import models, connections
from django.db.models.signals import pre_save

from .managers import ClipScopeManager
from .signals import ClipSignal
from ..core.tags.models import Tagged

@python_2_unicode_compatible
class Clip(Tagged):
    name = models.CharField(max_length=255)
    sql_query = models.TextField()
    slug = models.SlugField()
    user = models.ForeignKey('auth.User',
                             null=True,
                             blank=True,
                             on_delete=models.DO_NOTHING)
    database = models.ForeignKey('databases.Database', 
                                 on_delete=models.CASCADE)
    organization = models.ForeignKey('organizations.Organization',
                                     on_delete=models.CASCADE)

    objects = ClipScopeManager()

    original_sql_query = None

    def __unicode__(self):
        return self.name

    def cache_key(self):
        return "dataclips_{}".format(self.pk)

    # Override class constructor to get the initial sql_query 
    # to turn possible to make a comparsion when clip is saved
    def __init__(self, *args, **kwargs):
        super(Clip, self).__init__(*args, **kwargs)
        self.original_sql_query = self.sql_query

    # Override save to set the new sql_query when changed
    # to turn possible to make a comparsion when clip is saved
    def save(self, *args, **kwargs):
        super(Clip, self).save(*args, **kwargs)
        self.original_sql_query = self.sql_query

    def query_result(self):
        """
          Return a cached clip.sql_query executed
          suck like a:
          {'rows': [['foo', 'bar'], ['foo']], 'cols': ['col1', 'col2']}
        """

        cached = cache.get(self.cache_key())
        if cached is not None:
            return json.loads(cached)
        else:
            try:
                self.dump_query()
                return self.query_result()
            except Exception:
                return self.__exec_query()

    def dump_query(self):
        """
          Execute the sql query and make a cache
          accessible using:
          cache.get(self.cache_key())
        """

        cache.delete(self.cache_key())

        r = self.__exec_query()
        dump = json.dumps({'rows': r['rows'], 'cols': r['cols']})

        return cache.set(self.cache_key(), dump, 50000)

    def __exec_query(self):
        alias = 'databases_{}'.format(self.pk)

        connections.databases[alias] = {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': self.database.db_name,
            'USER': self.database.db_user,
            'PASSWORD': self.database.db_password,
            'HOST': self.database.db_host,
            'PORT': '',
        }

        conn = connections[alias]

        cursor = conn.cursor()
        sql = "select _.* from ({}) as _ limit 10000".format(self.sql_query)
        cursor.execute(sql)

        result_description = cursor.description
        result = cursor.fetchall()

        cursor.close()

        del connections.databases[alias]
        del connections[alias]

        self._sql_result = (result, result_description)
        return self.__format_query_result()

    def __format_query_result(self):
        result = self._sql_result

        # Create a array with all query result values
        # row_details = [[value for key,value in item.iteritems()] for item in restult[0]]
        row_details = []
        for item in result[0]:
            values = []
            for value in item:
                values.append(value)
            row_details.append(values)

        # Create a awway with all query result columns
        col_details = []
        for item in result[1]:
            col_details.append(item.name)

        return {'rows': row_details, 'cols': col_details}


pre_save.connect(ClipSignal.pre_save, sender=Clip)

askari/dataclips/forms.py
from django import forms
from .models import Clip


class ClipForm(forms.ModelForm):
    class Meta:
        model = Clip
        exclude = ['slug']

askari/dataclips/views.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.contrib import messages
from django.views.generic import (ListView, CreateView, UpdateView,
                                  DeleteView, DetailView)
from django.core.urlresolvers import reverse

from ..core.mixins import LoginRequiredViewMixin, GenericTemplateDataMixin
from .filters import ClipFilter
from .forms import ClipForm
from .models import Clip


@python_2_unicode_compatible
class ClipMixin(GenericTemplateDataMixin, LoginRequiredViewMixin):
    model = Clip

    def get_queryset(self):
        qs = super(ClipMixin, self).get_queryset()
        clips = Clip.objects.filter(organization=self.organization)
        return qs & clips


@python_2_unicode_compatible
class ClipFormMixin(ClipMixin):
    form_class = ClipForm

    def get_success_url(self):
        return reverse('dataclips:edit', kwargs={
            'pk': self.object.pk,
            'organization': self.organization.slug})


@python_2_unicode_compatible
class ClipListView(ClipMixin, ListView):
    def get_context_data(self, **kwargs):
        context = super(ClipListView, self).get_context_data(**kwargs)
        f = ClipFilter(self.request.GET, queryset=self.get_queryset())

        context_data = {'filter': f, 'object_list': f.qs}
        context.update(context_data)

        return context


@python_2_unicode_compatible
class ClipCreateView(ClipFormMixin, CreateView):
    pass


@python_2_unicode_compatible
class ClipUpdateView(ClipFormMixin, UpdateView):
    template_name = "dataclips/clip_update_and_show.html"

    def get_context_data(self, **kwargs):
        context = super(ClipUpdateView, self).get_context_data(**kwargs)

        executed_sql = self.object.query_result()
        try:
            executed_sql = self.object.query_result()
        except Exception as error:
            executed_sql = None
            messages.add_message(self.request, 
                                 messages.ERROR, 
                                 "{}".format(error))

        context_data = {'sql_exec': executed_sql}

        context.update(context_data)
        return context


class ClipDeleteView(ClipFormMixin, DeleteView):
    def get_success_url(self):
        return reverse('dataclips:list', kwargs={
            'organization': self.organization.slug})


class ClipPublicView(DetailView):
    model = Clip
    template_name = "dataclips/clip_public.html"

askari/dataclips/templates/dataclips/clip_confirm_delete.html
<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>

askari/dataclips/templates/dataclips/clip_detail.html
<h1>{{ object }}</h1>
<div style="witdh: 100%; background: #ececec;">{{ object.sql_query }}</div>
<br/>
<br/>
<h4>Total de linhas {{ object.exec_query.0|length }}</h4>
<br/>
<br/>
{% with object.exec_query as exec_query %}
<table>
  <thead>
    <tr>
      {% for header in exec_query.1 %}
      <th>
        {{ header.name }}
      </th>
      {% endfor %}
    </tr>
  </thead>

  <tbody>
    {% for row in exec_query.0 %}
      <tr>
      {% for column in row %}
        <td>{{ column }}</td>
      {% endfor %}
      </tr>
    {% endfor %}
  </tbody>

</table>
{% endwith %}

askari/dataclips/templates/dataclips/clip_form.html
{% extends 'app_template.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block custom_scripts %}
    <script src="//d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js"></script>
    <script type="text/javascript" src="{% static 'js/clip_form.js' %}"></script>
{% endblock %}

{% block main_content %}
    <section class="content-header">
        <h1>
            Dataclips
            <small>Novo</small>
        </h1>

    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <form action="" method="POST" novalidate>
                        <div class="box-body">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                        </div>

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </section>


{% endblock %}

askari/dataclips/templates/dataclips/clip_list.html
{% extends 'app_template.html' %}
{% block main_content %}
        <section class="content-header">
        <h1>
            Dataclips
            <small>listagem</small>
        </h1>

        <div class="pull-right">
            <a href="{% url 'dataclips:new' view.kwargs.organization %}" class="btn btn-success" style="margin-top: -55px;">
                <i class="fa fa-plus"></i>
                &nbsp;&nbsp;
                <strong>Adicionar</strong>
            </a>
        </div>
    </section>

    <section class="content">

        <div class="row">

            <div class="col-xs-12">

                <div class="box">

                  <div class='box-header'>
                      <form action="" method="get">
                        <fieldset>
                          <legend>Filtros</legend>
                          {{ filter.form.as_p }}
                          <button type="submit" class="btn btn-primary">Filtrar</button>
                        </fieldset>
                      </form>
                  </div>

                    <div class="box-body table-responsive no-padding">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Database</th>
                                    <th class="col-xs-1">Ações</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for resource in object_list %}
                                    <tr>
                                        <td>
                                            <a href="{% url 'dataclips:edit' pk=resource.pk organization=view.kwargs.organization %}">{{ resource.name }}</a>
                                        </td>
                                        <td>
                                            {{ resource.database }}
                                        </td>
                                        <td>
                                            <div class="btn-group">
                                                <a data-toggle="tooltip" data-placement="top" title="Editar" href="{% url 'dataclips:edit' pk=resource.pk organization=view.kwargs.organization %}" class="btn btn-default btn-sm">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <a data-toggle="tooltip" data-placement="top" title="Apagar" href="{% url 'dataclips:delete' pk=resource.pk organization=view.kwargs.organization %}" class="btn btn-default btn-sm">
                                                    <i class="fa fa-trash-o"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                {%  endfor %}
                            </tbody>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

askari/dataclips/templates/dataclips/clip_public.html
{% extends "base_clean_template.html" %}
{% load bootstrap3 %}

{% block title %} Askari | {{ object.name }} {% endblock %}

{% block main_content %}
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">

                    <div class="box-header">
                        <div class="box-title">
                            <h3>{{ object.name }}</h3>
                            <h5>Total de linhas {{ object.query_result.rows|length }}</h5>
                        </div>
                    </div>

                    {% with object.query_result as exec_query %}
                        <div class="box-body table-responsive">
                            <table class="table table-bordered table-hover dataTable">
                              <thead>
                                <tr>
                                  {% for header in exec_query.cols %}
                                  <th>
                                    {{ header }}
                                  </th>
                                  {% endfor %}
                                </tr>
                              </thead>

                              <tbody>
                                {% for row in exec_query.rows %}
                                  <tr>
                                  {% for column in row %}
                                    <td>{{ column }}</td>
                                  {% endfor %}
                                  </tr>
                                {% endfor %}
                              </tbody>

                            </table>
                        </div>
                    {% endwith %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

askari/dataclips/templates/dataclips/clip_update_and_show.html
{% extends 'app_template.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block custom_scripts %}
    <script src="//d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js"></script>
    <script type="text/javascript" src="{% static 'js/clip_form.js' %}"></script>
{% endblock %}

{% block main_content %}
    <section class="content-header">
        <h1>
            {{ object.name }}
            <small>visualização</small>
        </h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-xs-12">

                <div class="nav-tabs-custom">

                    <ul class="nav nav-tabs">
                        <li id="sql_tab">
                            <a href="#query_tab" class="sql-query-selector" data-toggle="tab">Query</a>
                        </li>
                        <li class="active">
                            <a href="#result_tab" data-toggle="tab">Resultado</a>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <div class="tab-pane" id="query_tab">
                            <form action="" method="POST" novalidate>
                                <div class="box-body">
                                    {% csrf_token %}
                                    {% bootstrap_form form %}
                                </div>

                                <div class="box-footer">
                                    <button type="submit" class="btn btn-primary">Salvar</button>
                                </div>
                            </form>
                        </div>

                        <div class="tab-pane active" id="result_tab">

                            {% if sql_exec %}
                                {% with sql_exec as exec_query %}
                                    <div class="table-responsive" style="overflow-x: auto;">
                                        <table class="table table-striped table-hover ">
                                          <thead>
                                            <tr>
                                              {% for header in exec_query.cols %}
                                              <th>
                                                {{ header }}
                                              </th>
                                              {% endfor %}
                                            </tr>
                                          </thead>

                                          <tbody>
                                            {% for row in exec_query.rows %}
                                              <tr>
                                              {% for column in row %}
                                                <td>{{ column }}</td>
                                              {% endfor %}
                                              </tr>
                                            {% endfor %}
                                          </tbody>

                                        </table>
                                    </div>
                                {% endwith %}

                            {% endif %}

                        </div>
                    </div>


                </div>
                <!--
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">
                            Query
                        </h3>
                    </div>
                    <div class="box-body">
                        <form action="" method="POST" novalidate>
                            <div class="box-body">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                            </div>

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Salvar</button>
                            </div>
                        </form>
                    </div>
                </div>
                -->
            </div>
        </div>

    </section>
{% endblock %}


{% if sql_exec %}
    <h4>Total de linhas {{ sql_exec.0|length }}</h4>
    <br/>
    {% with sql_exec as exec_query %}
        <table>
          <thead>
            <tr>
              {% for header in exec_query.1 %}
              <th>
                {{ header.name }}
              </th>
              {% endfor %}
            </tr>
          </thead>

          <tbody>
            {% for row in exec_query.0 %}
              <tr>
              {% for column in row %}
                <td>{{ column }}</td>
              {% endfor %}
              </tr>
            {% endfor %}
          </tbody>

        </table>
    {% endwith %}
{% endif %}