askari/core/urls.py
from django.conf.urls import patterns, include, url
from .views import DashboardView

urlpatterns = patterns(
    '',
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),

    url(r'^databases/', include('askari.databases.urls', 
                                namespace="databases")),
    url(r'^dataclips/', include('askari.dataclips.urls', 
                                namespace="dataclips")),
)

askari/core/user_profile/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

askari/databases/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here
from .views import (DatabaseCreateView, DatabaseListView, DatabaseUpdateView,
    DatabaseDeleteView,)

urlpatterns = patterns('',
    url(r'^new/', DatabaseCreateView.as_view(), name='new'),
    url(r'^(?P<pk>[\d]+)/edit$', DatabaseUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>[\d]+)/delete$', DatabaseDeleteView.as_view(), name='delete'),
    url(r'^$', DatabaseListView.as_view(), name='list')
)

askari/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .core.views import UserRegistrationView, UserLoginView


# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^login/$', 'django.contrib.auth.views.login', 
                     {"template_name": 'core/login.html'}, 
                     name='login'),

    url(r'^register/$', UserRegistrationView.as_view(), name='registration'),

    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', 
                      name='logout'),

    url(r'^success_login/$', UserLoginView.as_view(), name='login_redirect'),
    url(r'^(?P<organization>\w+)/', include('askari.core.urls')),
)

askari/core/models.py
from django.db import models
from django.contrib.auth.models import User
from ..databases.models import Database
from ..dataclips.models import Clip


class ProxyUser(User):

    def databases(self):
        '''
            Return the user databases
        '''
        return Database.objects.filter(user__pk=self.pk).all()

    def clips(self):
        '''
            Return the user dataclips
        '''
        return Clip.objects.filter(database__user__pk=self.pk).all()


    class Meta():
        proxy = True

askari/core/tags/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.template.defaultfilters import slugify

@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField("Nome", 
                            max_length=200, 
                            unique=True, 
                            db_index=True)

    slug = models.SlugField("Slug", db_index=True, max_length=150)

    __unicode__ = lambda self: self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs)

    class Meta:
        unique_together = ['slug', 'name']

@python_2_unicode_compatible
class Tagged(models.Model):
    tags = models.CharField("Tags", 
                            max_length=4000, 
                            blank=True,
                            null=True,
                            help_text="Lista de tags separadas por virgula")

    def save(self, *args, **kwargs):
        if self.tags:
            tags = filter(None, set(self.tags.split(',')))
            tags = map(str.strip, tags)

            for tag in tags:
                Tag.objects.get_or_create(name=tag)

            self.tags = ','.join(tags)

        super(Tagged, self).save(*args, **kwargs)

    def get_tags(self):
        if self.tags:
            tags = []

            for tag in self.tags.split(','):
                if tag in ["", " "]:
                    continue

                t, created = Tag.objects.get_or_create(name=tag)
                tags.append(t)

            return tags

    class Meta:
        abstract = True

askari/core/user_profile/models.py
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField('auth.User')
    organizations = models.ManyToManyField('organizations.Organization', 
                                           null=True, 
                                           blank=True)

askari/core/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.db import transaction
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from .user_profile.models import UserProfile
from ..organizations.models import Organization


User = get_user_model()


class UserRegistrationForm(UserCreationForm):
    organization_name = forms.CharField(required=True, label="Organização")
    organization_slug = forms.SlugField(required=True,
                                        label="Namespace (/namespace)")

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_organization_slug(self):
        try:
            Organization.objects.get(
                slug=self.cleaned_data['organization_slug'])
            raise forms.ValidationError("Essa organização já existe")
        except Organization.DoesNotExist:
            pass

    @transaction.atomic
    def save(self, *args, **kwargs):
        user = super(UserRegistrationForm, self).save(*args, **kwargs)

        profile = UserProfile.objects.create(user=user)
        organization = Organization.objects.create(
            name=self.cleaned_data['organization_name'],
            slug=self.cleaned_data['organization_slug'])

        profile.organizations.add(organization)

        return user

askari/core/user_profile/forms.py
from django import forms

# place form definition here

askari/core/user_profile/views.py
# Create your views here.

askari/core/views.py
from django.views.generic import TemplateView, CreateView, RedirectView
from django.core.urlresolvers import reverse
from .mixins import GenericTemplateDataMixin
from .forms import UserRegistrationForm


class DashboardView(GenericTemplateDataMixin, TemplateView):
    template_name = 'core/dashboard.html'


class UserLoginView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        org = self.request.user.userprofile.organizations.first()
        return reverse('dashboard', kwargs={'organization': org.slug})


class UserRegistrationView(CreateView):
    template_name = 'core/registration.html'
    form_class = UserRegistrationForm

    def get_success_url(self):
        return reverse('dashboard', self.organization.slug)

askari/core/templates/core/dashboard.html
{% extends 'app_template.html' %}

{% block main_content %}
    <section class="content-header">
        <h1>
            Dashboard
            <small>Inicio</small>
        </h1>

    </section>

    <section class="content">

        <div class="row">

            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>
                            {{ total_bases }}
                        </h3>
                        <p>
                            Banco de dados
                        </p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-gear-a"></i>
                    </div>
                    <a href="{% url 'databases:list' view.kwargs.organization %}" class="small-box-footer">
                        Ver todos <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>

            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3>
                            {{ total_clips }}
                        </h3>
                        <p>
                            Dataclips
                        </p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-clipboard"></i>
                    </div>
                    <a href="{% url 'dataclips:list' view.kwargs.organization %}" class="small-box-footer">
                        Ver todos <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>

        </div>

    </section>
{% endblock %}

askari/core/templates/core/login.html
{% extends "base_black_template.html" %}
{% load bootstrap3 %}

{% block title %} Askari | Login {% endblock %}

{% block main_content %}

    <div class="form-box" id="login-box">
        <div class="header">Área Restrita</div>


        <form method="post" action="" class="login-form">
            <div class="body bg-gray">
                {% csrf_token %}
                {% bootstrap_form form %}
            </div>
            <div class="footer">
                {% buttons %}
                    <button type="submit" class="btn bg-olive btn-block">
                        {% bootstrap_icon "lock" %} Entrar
                    </button>
                {% endbuttons %}

                <p><a href="#">I forgot my password</a></p>

                <a href="register.html" class="text-center">Register a new membership</a>
            </div>
        </form>

        <div class="margin text-center">
            <span>Sign in using social networks</span>
            <br/>
            <button class="btn bg-light-blue btn-circle"><i class="fa fa-facebook"></i></button>
            <button class="btn bg-aqua btn-circle"><i class="fa fa-twitter"></i></button>
            <button class="btn bg-red btn-circle"><i class="fa fa-google-plus"></i></button>

        </div>
    </div>
    
{% endblock %}

askari/core/templates/core/registration.html
{% extends "base_black_template.html" %}
{% load bootstrap3 %}

{% block title %} Askari | Login {% endblock %}

{% block main_content %}

    <div class="form-box" id="login-box">
        <div class="header">Área Restrita</div>


        <form method="post" action="" class="login-form" novalidate>
            <div class="body bg-gray">
                {% csrf_token %}
                {% bootstrap_form form %}
            </div>
            <div class="footer">
                {% buttons %}
                    <button type="submit" class="btn bg-olive btn-block">
                        {% bootstrap_icon "lock" %} Entrar
                    </button>
                {% endbuttons %}

                <a href="{% url 'login' %}" class="text-center">Já sou registrado</a>
            </div>
        </form>

        <div class="margin text-center">
            <span>Sign in using social networks</span>
            <br/>
            <button class="btn bg-light-blue btn-circle"><i class="fa fa-facebook"></i></button>
            <button class="btn bg-aqua btn-circle"><i class="fa fa-twitter"></i></button>
            <button class="btn bg-red btn-circle"><i class="fa fa-google-plus"></i></button>

        </div>
    </div>
    
{% endblock %}